# Generated by Django 4.1.7 on 2023-03-15 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NoteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('school', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('proposal_details', models.TextField()),
                ('proposal_submitted_by', models.CharField(max_length=255)),
                ('proposal_submitted_by_1', models.CharField(max_length=255)),
                ('name_of_hod', models.CharField(max_length=255)),
                ('name_of_director', models.CharField(max_length=255)),
                ('f_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notesheet_handle.facultydetails')),
            ],
        ),
        migrations.CreateModel(
            name='NoteSheetAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.IntegerField()),
                ('f_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notesheet_handle.notesheet')),
            ],
        ),
    ]
